---
name: Validar arquivos YAML

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  validate-yaml:
    name: Verificar sintaxe dos YAMLs
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Validar YAMLs com yamllint
        uses: ibiqlik/action-yamllint@v3

